apiVersion: apps/v1
kind: Deployment
metadata:
  name: ostad-ui
  namespace: kwoshik
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ostad-ui
  template:
    metadata:
      labels:
        app: ostad-ui
    spec:
      containers:
        - name: ostad-ui
          image: rootovertwo/ostad-ui:latest
          ports:
            - containerPort: 5173
          env:
            - name: MONGO_URI
              valueFrom:
                configMapKeyRef:
                  name: mongo-configmap
                  key: mongo-uri
