apiVersion: apps/v1
kind: Deployment
metadata:
  name: ostad-server
  namespace: ostad
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ostad-server
  template:
    metadata:
      labels:
        app: ostad-server
    spec:
      containers:
        - name: ostad-server
          image: rootovertwo/ostad-server:latest
          ports:
            - containerPort: 5050
          env:
            - name: MONGO_URI
              valueFrom:
                configMapKeyRef:
                  name: mongo-configmap
                  key: mongo-uri
